# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=dox]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: interpret-trailer
        name: interpret-trailer
        language: system
        entry: git interpret-trailers
        args: [--trim-empty,--in-place,--unfold]
        stages: [commit-msg]
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
